"use client";

import { useQuery } from "convex/react";
import { api } from "../../../../../convex/_generated/api";
import { useSearchParams } from "next/navigation";
import { useEffect, useState } from "react";
import { Loader2 } from "lucide-react";

export default function PrintReportPage() {
  const searchParams = useSearchParams();
  const module = searchParams.get("module") || "all";
  const dataType = searchParams.get("dataType") || "bills";
  const fromDate = searchParams.get("fromDate") || "";
  const toDate = searchParams.get("toDate") || "";
  
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
  }, []);

  const data = useQuery(api.reports.getExportData, mounted && fromDate && toDate ? {
    module,
    dataType,
    fromDate,
    toDate
  } : "skip");

  useEffect(() => {
    if (data !== undefined && data !== null) {
      // Small delay to allow React to render the table before calling print
      setTimeout(() => {
        window.print();
      }, 500);
    }
  }, [data]);

  if (!mounted || data === undefined) {
    return (
      <div className="flex items-center justify-center min-h-screen bg-white">
        <Loader2 className="w-8 h-8 animate-spin text-green-600" />
        <span className="ml-2 text-gray-600 font-medium">Preparing Report for Print...</span>
      </div>
    );
  }

  if (data === null || data.length === 0) {
    return (
      <div className="p-8 text-center text-gray-500 font-medium bg-white min-h-screen">
        <h2 className="text-xl mb-2">No data found for the selected criteria.</h2>
        <p className="text-sm">Please try a different date range or module.</p>
        <button onClick={() => window.close()} className="mt-6 px-6 py-2 bg-gray-100 text-gray-700 rounded-lg hover:bg-gray-200 transition-colors">
          Close Window
        </button>
      </div>
    );
  }

  const headers = Object.keys(data[0]);

  return (
    <div className="p-8 bg-white min-h-screen text-black print:p-0">
      <div className="mb-6 border-b border-gray-200 pb-4">
        <h1 className="text-2xl font-bold uppercase tracking-wide text-gray-900">Report Export</h1>
        <div className="text-sm text-gray-600 mt-3 grid grid-cols-2 gap-x-8 gap-y-2 max-w-lg">
          <p><span className="font-semibold text-gray-800">Module:</span> {module.toUpperCase()}</p>
          <p><span className="font-semibold text-gray-800">Data Type:</span> {dataType.toUpperCase()}</p>
          <p><span className="font-semibold text-gray-800">From Date:</span> {fromDate}</p>
          <p><span className="font-semibold text-gray-800">To Date:</span> {toDate}</p>
        </div>
      </div>

      <table className="w-full text-sm border-collapse">
        <thead>
          <tr>
            {headers.map(h => (
              <th key={h} className="border-b-2 border-gray-800 pb-2 text-left font-bold text-gray-900 whitespace-nowrap pr-4">
                {h}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {data.map((row, idx) => (
            <tr key={idx} className="border-b border-gray-200 break-inside-avoid">
              {headers.map(h => (
                <td key={h} className="py-2 pr-4 text-gray-800 align-top">
                  {String(row[h] ?? "")}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>

      <div className="mt-8 text-center text-xs text-gray-400 print:block break-inside-avoid">
        Generated by Shyam Clinic & Restaurant System • {new Date().toLocaleString()}
      </div>
    </div>
  );
}
